services:
  redis:
    image: redis:7-alpine
    container_name: ble_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ble_network
    
  subscriber:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    container_name: ble_topic_subscriber
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    networks:
      - ble_network
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ble_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - subscriber
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - ble_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  ble_network:
    driver: bridge 